[versions]
javagi = "0.14.1"
jdk = "22"
cairo = "1.18.4.2"
picocli = "4.7.7"
javapoet = "1.13.0"
jspecify = "1.0.0"
junit = "6.0.3"
mavenpublish = "0.36.0"

[libraries]
javagi-generator = { module = "org.java-gi:generator", version.ref = "javagi" }
cairo = { module = "io.github.jwharm.cairobindings:cairo", version.ref = "cairo" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mavenpublish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenpublish" }
