[versions]
javagi = "0.12.0"
jdk = "22"
cairo = "1.18.4.1"
picocli = "4.7.7"
javapoet = "1.13.0"
annotations = "26.0.2"
junit = "5.12.2"

[libraries]
javagi-generator = { module = "io.github.jwharm.javagi:generator", version.ref = "javagi" }
cairo = { module = "io.github.jwharm.cairobindings:cairo", version.ref = "cairo" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
